### ISSUE TITLE
Training with multiple GPUs

### ISSUE THREAD

**Issue by a14en9** [martinimass/pointnet1-2-pytorch#1]
Hi @martinimass,

Thank you for posting this repo. I tried using multiple GPUs to train a model, but I found that their usage is always hopping, sometimes each GPU can be over 70% usage, but most of the time two of them are 0 and the other is less than 10%. Is there any chance for you to provide an example of using multiple GPUs to train the model?

Thanks in advance!

**Comment by martinimass** [comment]
Hi @cvhabitat,
I am sorry but I never tested the code on more than one GPU. My code is based on [yanx27](https://github.com/yanx27/Pointnet_Pointnet2_pytorch), I adapted it to use the ArCH dataset. You could try asking the same question to him.
Best regards

**Comment by a14en9** [comment]
Thank you!
